apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-docker-app
  template:
    metadata:
      labels:
        app: node-docker-app
    spec:
      containers:
      - name: node-docker-app
        image: pratham1310/node-docker-app:latest
        ports:
        - containerPort: 3000